[package]
name = "rcpr"
version = "0.1.0"
authors = ["Jarat <drobny2@illinois.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.13.1"
ndarray-linalg = "0.12.1"
time = ""

[lib]
crate-type = ["rlib"]
